// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool({
  name: "list_clients",
  title: "Listar clientes",
  description: "Lista os clientes do CRM Altus Media a que o utilizador autenticado tem acesso.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("N\xFAmero m\xE1ximo de clientes a devolver (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await sb(ctx).from("clients").select("id, business_name, contact_name, contact_email, status, monthly_revenue, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool2({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista os leads capturados pelos formul\xE1rios da Altus Media.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("N\xFAmero m\xE1ximo de leads (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("leads").select("*").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-whatsapp-conversations.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_whatsapp_conversations_default = defineTool3({
  name: "list_whatsapp_conversations",
  title: "Listar conversas de WhatsApp",
  description: "Lista as conversas recentes dos agentes de WhatsApp geridos pela Altus Media.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional(),
    client_id: z3.string().uuid().optional().describe("Filtrar por cliente espec\xEDfico.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, client_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = sb3(ctx).from("whatsapp_conversations").select("id, contact_name, contact_phone, last_message, last_message_at, lead_status, sentiment, messages_count, client_id").order("last_message_at", { ascending: false }).limit(limit ?? 25);
    if (client_id) q = q.eq("client_id", client_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gkntdgcttakidccehcvl";
var mcp_default = defineMcp({
  name: "altus-media-mcp",
  title: "Altus Media",
  version: "0.1.0",
  instructions: "Ferramentas do CRM da Altus Media. Usa `list_clients`, `list_leads` e `list_whatsapp_conversations` para consultar dados. Todas as ferramentas respeitam as pol\xEDticas de acesso do utilizador autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_clients_default, list_leads_default, list_whatsapp_conversations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
